run:
  timeout: 3m

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosec
    - revive

linters-settings:
  gocyclo:
    min-complexity: 15
  
  revive:
    severity: warning

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec