package main

import "fmt"

// searchMatrix searches for a target value in a 2D matrix
func searchMatrix(matrix [][]int, target int) bool {
	if len(matrix) == 0 || len(matrix[0]) == 0 {
		return false
	}

	i := 0
	j := 0
	k := len(matrix) - 1
	l := len(matrix[0]) - 1
	M := matrix
	t := target

	// Check if target is outside the matrix range
	if M[i][j] > t || M[k][l] < t {
		return false
	}

	// Shrink the search area by eliminating rows/columns
	for i < k && j < l {
		if M[i][j] > t || M[i][l] < t {
			i++
		} else if M[i][j] > t || M[k][j] < t {
			j++
		} else if M[k][j] > t || M[k][l] < t {
			k--
		} else if M[i][l] > t || M[k][l] < t {
			l--
		} else if M[i][j] == t || M[i][l] == t || M[k][j] == t || M[k][l] == t {
			return true
		}
	}

	// Search in remaining row or column
	if i == k {
		// Search remaining row
		for col := j; col <= l; col++ {
			if M[i][col] == t {
				return true
			}
		}
		return false
	} else {
		// Search remaining column
		for row := i; row <= k; row++ {
			if M[row][j] == t {
				return true
			}
		}
		return false
	}
}

func main() {
	// Example case, generated by AI
	matrix := [][]int{
		{1, 4, 7, 11, 15},
		{2, 5, 8, 12, 19},
		{3, 6, 9, 16, 22},
		{10, 13, 14, 17, 24},
		{18, 21, 23, 26, 30},
	}

	target := 5
	result := searchMatrix(matrix, target)
	fmt.Printf("Target %d found: %t\n", target, result)

	target = 20
	result = searchMatrix(matrix, target)
	fmt.Printf("Target %d found: %t\n", target, result)
}
